---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bdlpsipeka/public_html
    - /bin/cp -a public/. $DEPLOYPATH
    - /bin/sed -i 's|\.\./vendor/autoload\.php|/home/bdlpsipeka/repositories/absen-sidang/vendor/autoload.php|g' $DEPLOYPATH/index.php
    - /bin/sed -i 's|\.\./bootstrap/app\.php|/home/bdlpsipeka/repositories/absen-sidang/bootstrap/app.php|g' $DEPLOYPATH/index.php